import {getDocument,GlobalWorkerOptions} from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
GlobalWorkerOptions.workerSrc=workerUrl;
let loadingTask=null,pdf=null,renderTask=null,job=0,renderJob=0;
export async function release(){job++;renderJob++;if(renderTask){renderTask.cancel();renderTask=null;}const task=loadingTask;loadingTask=null;pdf=null;if(task)await task.destroy();}
export async function loadPdf(data,onProgress=()=>{}){await release();const token=job;const task=getDocument({...typeof data==='string'?{url:data}:{data:new Uint8Array(data)},cMapUrl:'/pdfjs/cmaps/',cMapPacked:true,standardFontDataUrl:'/pdfjs/standard_fonts/',wasmUrl:'/pdfjs/wasm/',iccUrl:'/pdfjs/iccs/'});loadingTask=task;task.onPassword=()=>{task.destroy();};try{const doc=await task.promise;if(token!==job)return null;if(doc.numPages>30){await release();throw Error('최대 30페이지까지 지원합니다. / Maximum 30 pages.');}pdf=doc;const pages=[];for(let n=1;n<=doc.numPages;n++){const page=await doc.getPage(n);const content=await page.getTextContent();if(token!==job)return null;const lines=[];let y=null;for(const item of content.items){if(!('str'in item))continue;if(y!==null&&Math.abs(item.transform[5]-y)>3)lines.push('\n');lines.push(item.str+' ');y=item.transform[5];}pages.push({pdfPage:n,text:lines.join('').trim()});onProgress(n,doc.numPages);}return {pageCount:doc.numPages,pages};}catch(e){if(token!==job)return null;throw Error(`PDF를 읽을 수 없습니다. 암호·손상 여부를 확인하세요. / PDF unavailable: ${e.message}`);}}
export const hasPdf=()=>!!pdf;
export async function renderPage(canvas,pageNumber,scale=1){const renderToken=++renderJob;if(!pdf)throw Error('PDF를 다시 첨부해 주세요. / Reattach the PDF.');if(renderTask){renderTask.cancel();try{await renderTask.promise;}catch{}renderTask=null;}const doc=pdf;const page=await doc.getPage(pageNumber);if(pdf!==doc||renderToken!==renderJob)return;const viewport=page.getViewport({scale});const dpr=Math.min(devicePixelRatio||1,2,Math.sqrt(5000000/(viewport.width*viewport.height)));canvas.width=Math.floor(viewport.width*dpr);canvas.height=Math.floor(viewport.height*dpr);canvas.style.width=`${viewport.width}px`;canvas.style.height=`${viewport.height}px`;renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport,transform:[dpr,0,0,dpr,0,0]});try{await renderTask.promise;}catch(e){if(e.name!=='RenderingCancelledException')throw e;}}
export function cancelRender(){renderJob++;renderTask?.cancel();}
