import test from 'node:test';
import assert from 'node:assert/strict';
import {sampleState} from '../src/data/sample.js';
import {sampleDraft} from '../src/services/content.js';
import {initialState,invalidate,editDraft,reviewErrors} from '../src/state.js';
import {makePrompt} from '../src/services/prompt.js';
import {parseResult} from '../src/services/import.js';
import {snapshot} from '../src/services/storage.js';
import {exportText} from '../src/services/export.js';
test('All nine bilingual sample combinations use confirmed facts and distinct formats',()=>{const s=sampleState('ko');const bodies=new Set();for(const audience of ['buyer','engineer','purchasing'])for(const format of ['website','email','linkedin']){s.settings.customerType=audience;s.settings.contentType=format;const d=sampleDraft(s);for(const l of ['ko','en']){assert.match(d[l].body,/7 Nm/);assert.match(d[l].body,/20 Nm/);assert.match(d[l].body,/0.68 kg/);assert.match(d[l].body,/BCSA 070-019-I/);}bodies.add(d.en.body);}assert.equal(bodies.size,9);s.product.facts.find(f=>f.field==='ratedTorque').value='8';assert.match(sampleDraft(s).ko.body,/8 Nm/);assert.match(sampleDraft(s).en.body,/8 Nm/);});
test('Review invalidates on input and translation edits',()=>{const s=sampleState('ko');s.draft=sampleDraft(s);s.questions.forEach(q=>q.status='excluded');assert.deepEqual(reviewErrors(s,true),[]);editDraft(s,'en','body','Changed');assert.ok(reviewErrors(s,true).includes('translation'));invalidate(s);assert.ok(reviewErrors(s,true).includes('revision'));});
function fixture(s){s.request=makePrompt(s,[]);return {schemaVersion:1,requestId:s.request.id,inputRevision:s.inputRevision,modelId:s.product.modelId,summary:[],terms:[],claims:[{text:'7 Nm',sourceIds:['src-1']}],questions:[],drafts:{ko:{title:'제목',body:'본문'},en:{title:'Subject',body:'Body'}}};}
test('Import rejects malformed, stale, wrong-model and unknown-source results without mutation',()=>{const s=sampleState('ko');s.draft=sampleDraft(s);const before=JSON.stringify(s.draft);const r=fixture(s);assert.equal(parseResult(JSON.stringify(r),s).draft.en.body,'Body');assert.equal(parseResult('```json\n'+JSON.stringify(r)+'\n```',s).draft.ko.body,'본문');assert.throws(()=>parseResult('{bad',s));assert.throws(()=>parseResult(JSON.stringify({...r,modelId:'wrong'}),s));assert.throws(()=>parseResult(JSON.stringify({...r,requestId:'old'}),s));r.claims[0].sourceIds=['fake'];assert.throws(()=>parseResult(JSON.stringify(r),s),/Unknown sources/);assert.equal(JSON.stringify(s.draft),before);invalidate(s);assert.throws(()=>parseResult(JSON.stringify(r),s));});
test('Prompt length is bounded and only selected source pages leave the app',()=>{const s=sampleState('ko');s.document.pages=[{pdfPage:1,text:'included'},{pdfPage:2,text:'private unselected'}];const p=makePrompt(s,[1]);assert.match(p.text,/included/);assert.doesNotMatch(p.text,/private unselected/);s.document.pages[0].text='x'.repeat(40001);assert.throws(()=>makePrompt(s,[1]));});
test('Snapshots exclude extracted text and request payloads',()=>{const s=sampleState('ko');s.document.pages=[{pdfPage:1,text:'private'}];s.request={text:'private'};const snap=snapshot(s);assert.deepEqual(snap.document.pages,[]);assert.equal(snap.request,null);assert.equal(s.document.pages.length,1);});
test('New documents start without sample facts and export includes review status',()=>{assert.equal(initialState().product.facts.length,0);const s=sampleState('ko');s.draft=sampleDraft(s);assert.match(exportText(s),/Unreviewed draft/);assert.match(exportText(s),/PDF 5/);assert.match(exportText(s),/Sample template/);});
